USE OUTSYSTEMS_LOG;

-----------------------------------------------------------------------------------------------------------------------------------------------------------
--SCRIPT TO DROP TEMP TABLES
-----------------------------------------------------------------------------------------------------------------------------------------------------------
DROP TABLE #TMP_MODULES;
DROP TABLE #TMP_INT_LOGS;
DROP TABLE #TMP_FINAL_LOGS;

-----------------------------------------------------------------------------------------------------------------------------------------------------------
--CREATE TEMPTABLE WITH MODULE INFORMATION
-----------------------------------------------------------------------------------------------------------------------------------------------------------
SELECT	APP.ID AS APPID, APP.NAME AS APPLICATIONNAME, APP.DESCRIPTION AS APPDESCRIPTION, ESP.ID AS ESPACEID, ESP.NAME AS ESPACENAME
INTO	#TMP_MODULES
FROM	OUTSYSTEMS.DBO.OSSYS_APP_DEFINITION_MODULE DM INNER JOIN OUTSYSTEMS.DBO.OSSYS_APPLICATION APP ON (DM.APPLICATION_ID = APP.ID)
										INNER JOIN OUTSYSTEMS.DBO.OSSYS_MODULE MO ON (MO.ID = DM.MODULE_ID)
										INNER JOIN OUTSYSTEMS.DBO.OSSYS_ESPACE ESP ON (ESP.ID = MO.ESPACE_ID)
WHERE	1 = 1
AND		APP.NAME LIKE '%SOA%';


-----------------------------------------------------------------------------------------------------------------------------------------------------------
--COLLECT LOGS FROM LOG TABLES

--OSLOG_INTEGRATION_X: ONE LOG TABLE BY WEEK
-- REQUEST_KEY: AGREGATES ALL CALLS TO CONSUMED SERVICES BY THE SAME ID
-----------------------------------------------------------------------------------------------------------------------------------------------------------
SELECT	MDL.APPLICATIONNAME, MDL.ESPACENAME, ILOG.INSTANT, ILOG.DURATION, ILOG.TYPE, ILOG.ENDPOINT, ILOG.ACTION, ILOG.ERROR_ID, ILOG.EXECUTED_BY, ILOG.IS_EXPOSE, ILOG.REQUEST_KEY
INTO	#TMP_INT_LOGS
FROM	OSLOG_INTEGRATION_0 ILOG INNER JOIN #TMP_MODULES MDL ON (MDL.ESPACEID = ILOG.ESPACE_ID);

INSERT INTO #TMP_INT_LOGS
SELECT	MDL.APPLICATIONNAME, MDL.ESPACENAME, ILOG.INSTANT, ILOG.DURATION, ILOG.TYPE, ILOG.ENDPOINT, ILOG.ACTION, ILOG.ERROR_ID, ILOG.EXECUTED_BY, ILOG.IS_EXPOSE, ILOG.REQUEST_KEY
FROM	OSLOG_INTEGRATION_1 ILOG INNER JOIN #TMP_MODULES MDL ON (MDL.ESPACEID = ILOG.ESPACE_ID);

INSERT INTO #TMP_INT_LOGS
SELECT	MDL.APPLICATIONNAME, MDL.ESPACENAME, ILOG.INSTANT, ILOG.DURATION, ILOG.TYPE, ILOG.ENDPOINT, ILOG.ACTION, ILOG.ERROR_ID, ILOG.EXECUTED_BY, ILOG.IS_EXPOSE, ILOG.REQUEST_KEY
FROM	OSLOG_INTEGRATION_2 ILOG INNER JOIN #TMP_MODULES MDL ON (MDL.ESPACEID = ILOG.ESPACE_ID);

INSERT INTO #TMP_INT_LOGS
SELECT	MDL.APPLICATIONNAME, MDL.ESPACENAME, ILOG.INSTANT, ILOG.DURATION, ILOG.TYPE, ILOG.ENDPOINT, ILOG.ACTION, ILOG.ERROR_ID, ILOG.EXECUTED_BY, ILOG.IS_EXPOSE, ILOG.REQUEST_KEY
FROM	OSLOG_INTEGRATION_3 ILOG INNER JOIN #TMP_MODULES MDL ON (MDL.ESPACEID = ILOG.ESPACE_ID);

INSERT INTO #TMP_INT_LOGS
SELECT	MDL.APPLICATIONNAME, MDL.ESPACENAME, ILOG.INSTANT, ILOG.DURATION, ILOG.TYPE, ILOG.ENDPOINT, ILOG.ACTION, ILOG.ERROR_ID, ILOG.EXECUTED_BY, ILOG.IS_EXPOSE, ILOG.REQUEST_KEY
FROM	OSLOG_INTEGRATION_4 ILOG INNER JOIN #TMP_MODULES MDL ON (MDL.ESPACEID = ILOG.ESPACE_ID);

INSERT INTO #TMP_INT_LOGS
SELECT	MDL.APPLICATIONNAME, MDL.ESPACENAME, ILOG.INSTANT, ILOG.DURATION, ILOG.TYPE, ILOG.ENDPOINT, ILOG.ACTION, ILOG.ERROR_ID, ILOG.EXECUTED_BY, ILOG.IS_EXPOSE, ILOG.REQUEST_KEY
FROM	OSLOG_INTEGRATION_5 ILOG INNER JOIN #TMP_MODULES MDL ON (MDL.ESPACEID = ILOG.ESPACE_ID);

INSERT INTO #TMP_INT_LOGS
SELECT	MDL.APPLICATIONNAME, MDL.ESPACENAME, ILOG.INSTANT, ILOG.DURATION, ILOG.TYPE, ILOG.ENDPOINT, ILOG.ACTION, ILOG.ERROR_ID, ILOG.EXECUTED_BY, ILOG.IS_EXPOSE, ILOG.REQUEST_KEY
FROM	OSLOG_INTEGRATION_6 ILOG INNER JOIN #TMP_MODULES MDL ON (MDL.ESPACEID = ILOG.ESPACE_ID);

INSERT INTO #TMP_INT_LOGS
SELECT	MDL.APPLICATIONNAME, MDL.ESPACENAME, ILOG.INSTANT, ILOG.DURATION, ILOG.TYPE, ILOG.ENDPOINT, ILOG.ACTION, ILOG.ERROR_ID, ILOG.EXECUTED_BY, ILOG.IS_EXPOSE, ILOG.REQUEST_KEY
FROM	OSLOG_INTEGRATION_7 ILOG INNER JOIN #TMP_MODULES MDL ON (MDL.ESPACEID = ILOG.ESPACE_ID);

INSERT INTO #TMP_INT_LOGS
SELECT	MDL.APPLICATIONNAME, MDL.ESPACENAME, ILOG.INSTANT, ILOG.DURATION, ILOG.TYPE, ILOG.ENDPOINT, ILOG.ACTION, ILOG.ERROR_ID, ILOG.EXECUTED_BY, ILOG.IS_EXPOSE, ILOG.REQUEST_KEY
FROM	OSLOG_INTEGRATION_8 ILOG INNER JOIN #TMP_MODULES MDL ON (MDL.ESPACEID = ILOG.ESPACE_ID);

INSERT INTO #TMP_INT_LOGS
SELECT	MDL.APPLICATIONNAME, MDL.ESPACENAME, ILOG.INSTANT, ILOG.DURATION, ILOG.TYPE, ILOG.ENDPOINT, ILOG.ACTION, ILOG.ERROR_ID, ILOG.EXECUTED_BY, ILOG.IS_EXPOSE, ILOG.REQUEST_KEY
FROM	OSLOG_INTEGRATION_9 ILOG INNER JOIN #TMP_MODULES MDL ON (MDL.ESPACEID = ILOG.ESPACE_ID);


-----------------------------------------------------------------------------------------------------------------------------------------------------------
--CALUCLATE METRICS
-----------------------------------------------------------------------------------------------------------------------------------------------------------
SELECT	APPLICATIONNAME, ESPACENAME, CONVERT(DATE, LG.INSTANT) INSTDATE, CONVERT(TIME, LG.INSTANT) INSTTIME, ENDPOINT, ACTION, DURATION, 
		CASE WHEN ERROR_ID = '' THEN 0 ELSE 1 END HAS_ERROR
INTO	#TMP_FINAL_LOGS
FROM	#TMP_INT_LOGS LG;



SELECT	APPLICATIONNAME, 
		ESPACENAME, 
		ACTION, 
		COUNT(*) AS EXECUTIONS, 
		SUM(HAS_ERROR) AS ERRORS, 
		(SUM(HAS_ERROR) * 100) / COUNT(*) AS PERC_ERRORS,
		MAX(DURATION) AS MAX_DURATION_MS, 
		AVG(duration) AS AVG_DURATION_MS
FROM	#TMP_FINAL_LOGS
--WHERE	INSTDATE = '2021-04-05'
GROUP BY APPLICATIONNAME, ESPACENAME, ACTION
ORDER BY 8 desc


-----------------------------------------------------------------------------------------------------------------------------------------------------------
--Other scripts
-----------------------------------------------------------------------------------------------------------------------------------------------------------


select	Request_Key, COUNT(*)
FROM	#TMP_INT_LOGS
GROUP BY REQUEST_KEY 
HAVING COUNT(*) > 1

select	*
from	#TMP_INT_LOGS
WHERE	request_key = '6c4f0db2-10f0-44f6-b356-e52c63bbc41e'

